import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

// Main styles
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scrollContent: { paddingBottom: 120 },
  backgroundGlowTop: {
    position: 'absolute',
    top: 60,
    right: -40,
    width: 220,
    height: 220,
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
    borderRadius: 999,
  },
  backgroundGlowBottom: {
    position: 'absolute',
    top: 360,
    left: -60,
    width: 180,
    height: 180,
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderRadius: 999,
  },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  headerSubtitle: { fontSize: 12, color: '#94A3B8', fontWeight: '600' },
  headerTitle: { fontSize: 28, fontWeight: '700', color: '#0F172A' },
  newBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
  newBadgeText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  summaryCard: { marginHorizontal: 20, borderRadius: 24, padding: 18, overflow: 'hidden' },
  summaryDecorationTop: { position: 'absolute', top: -20, right: -10, width: 120, height: 120, borderRadius: 60, backgroundColor: 'rgba(139, 92, 246, 0.2)' },
  summaryDecorationBottom: { position: 'absolute', bottom: -20, left: -20, width: 90, height: 90, borderRadius: 45, backgroundColor: 'rgba(59, 130, 246, 0.18)' },
  summaryRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  summaryIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: 'rgba(139, 92, 246, 0.8)', alignItems: 'center', justifyContent: 'center' },
  summaryTextWrap: { flex: 1 },
  summaryTitle: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },
  summarySubtitle: { fontSize: 12, color: 'rgba(255,255,255,0.7)', marginTop: 4 },
  markAllBtn: { marginTop: 14, borderRadius: 14, paddingVertical: 10, paddingHorizontal: 12, backgroundColor: 'rgba(255,255,255,0.15)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  markAllText: { color: '#FFFFFF', fontWeight: '600' },
  tabsRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, marginTop: 16 },
  tabChip: { paddingVertical: 8, paddingHorizontal: 14, borderRadius: 999, backgroundColor: '#FFFFFF', shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 6 },
  tabChipActive: { backgroundColor: '#6366F1' },
  tabChipText: { fontSize: 12, color: '#64748B', fontWeight: '600' },
  tabChipTextActive: { color: '#FFFFFF' },
  section: { paddingHorizontal: 20, marginTop: 18 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.8, color: '#94A3B8', fontWeight: '700' },
  sectionCount: { fontSize: 13, color: '#64748B', fontWeight: '700' },
  card: { borderRadius: 18, padding: 16, overflow: 'hidden' },
  newCard: { borderWidth: 1, borderColor: '#DDD6FE' },
  assignmentHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  assignmentIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#FB923C', alignItems: 'center', justifyContent: 'center' },
  assignmentInfo: { flex: 1 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  assignmentTitle: { fontSize: 15, fontWeight: '700', color: '#0F172A' },
  editedBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#F1F5F9', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  editedBadgeText: { fontSize: 10, fontWeight: '600', color: '#64748B' },
  editedCard: { borderWidth: 2, borderColor: '#F59E0B' },
  editedBanner: { 
    backgroundColor: '#FEF3C7', 
    paddingVertical: 10, 
    paddingHorizontal: 14, 
    marginBottom: 12, 
    borderRadius: 10, 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  editedBannerText: { fontSize: 14, fontWeight: '700', color: '#B45309', flex: 1 },
  editedBannerSubtext: { fontSize: 11, color: '#92400E' },
  changesPreview: { 
    backgroundColor: '#FFFBEB', 
    paddingVertical: 8, 
    paddingHorizontal: 12, 
    marginTop: 8, 
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  changesPreviewLabel: { fontSize: 11, fontWeight: '600', color: '#92400E', marginBottom: 4 },
  changesPreviewText: { fontSize: 12, color: '#B45309', lineHeight: 16 },
  assignmentSubtitle: { fontSize: 12, color: '#64748B' },
  assignmentFromRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 4, flexWrap: 'wrap' },
  circleChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F3E8FF', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, gap: 4 },
  circleChipEmoji: { fontSize: 10 },
  circleChipText: { fontSize: 10, fontWeight: '600', color: '#7C3AED' },
  missionNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginTop: 12, backgroundColor: '#F8FAFC', padding: 10, borderRadius: 10, borderLeftWidth: 3, borderLeftColor: '#CBD5E1' },
  missionNoteText: { flex: 1, fontSize: 13, color: '#475569', lineHeight: 18 },
  missionDetails: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12, flexWrap: 'wrap' },
  detailChip: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#F3E8FF', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  detailChipText: { fontSize: 11, fontWeight: '600', color: '#7C3AED' },
  xpChip: { backgroundColor: '#FEF3C7' },
  missionTags: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10, flexWrap: 'wrap' },
  tagChip: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  repeatTag: { backgroundColor: '#DBEAFE' },
  repeatTagText: { fontSize: 10, fontWeight: '600', color: '#2563EB' },
  proofTag: { backgroundColor: '#EDE9FE' },
  proofTagText: { fontSize: 10, fontWeight: '600', color: '#7C3AED' },
  nudgeTag: { backgroundColor: '#D1FAE5' },
  nudgeTagText: { fontSize: 10, fontWeight: '600', color: '#10B981' },
  assignmentMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, borderWidth: 1 },
  statusText: { fontSize: 10, fontWeight: '700' },
  assignmentTime: { fontSize: 12, color: '#94A3B8' },
  cardActions: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 14, flexWrap: 'wrap' },
  primaryAction: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#ECFDF5', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 12 },
  primaryActionText: { fontSize: 12, fontWeight: '700', color: '#10B981' },
  secondaryAction: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#F1F5F9', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 12 },
  secondaryActionText: { fontSize: 12, fontWeight: '600', color: '#64748B' },
  secondaryDisabled: { opacity: 0.6 },
  iconAction: { width: 44, height: 44, borderRadius: 12, backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center' },
  feedbackChip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12 },
  feedbackSuccess: { backgroundColor: '#ECFDF5' },
  feedbackInfo: { backgroundColor: '#F1F5F9' },
  feedbackText: { fontSize: 12, fontWeight: '600', color: '#475569' },
  activityHeader: { flexDirection: 'row', gap: 12 },
  activityIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  activityBody: { flex: 1 },
  activityTitleRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  activityTitle: { fontSize: 15, fontWeight: '700', color: '#0F172A', flex: 1 },
  activitySubtitle: { fontSize: 12, color: '#64748B', marginTop: 4 },
  activityMeta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  activityTime: { fontSize: 12, color: '#94A3B8' },
  pulseDot: { width: 8, height: 8, borderRadius: 4 },
  emptyCard: { borderRadius: 20, padding: 24, alignItems: 'center' },
  emptyIcon: { width: 60, height: 60, borderRadius: 20, backgroundColor: '#ECFDF5', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: '#0F172A' },
  emptySubtitle: { fontSize: 12, color: '#94A3B8', textAlign: 'center', marginTop: 6 },
  emptyBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#ECFDF5', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, marginTop: 12 },
  emptyBadgeText: { fontSize: 11, color: '#10B981', fontWeight: '600' },
  emptyActions: { flexDirection: 'row', gap: 12, marginTop: 16 },
  emptyActionPrimary: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, backgroundColor: '#DBEAFE' },
  emptyActionSecondary: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, backgroundColor: '#EDE9FE' },
  emptyActionText: { fontSize: 12, color: '#2563EB', fontWeight: '600' },
});

// Detail Modal Styles
export const detailModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingBottom: 40,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: '#E2E8F0',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  editedSection: {
    backgroundColor: '#FEF3C7',
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#F59E0B',
  },
  editedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  editedTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#B45309',
  },
  editedSubtitle: {
    fontSize: 13,
    color: '#92400E',
    marginBottom: 12,
  },
  changesList: {
    backgroundColor: '#FFFBEB',
    borderRadius: 10,
    padding: 12,
  },
  changesLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#92400E',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  changeItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 6,
  },
  changeBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#F59E0B',
    marginTop: 6,
  },
  changeText: {
    fontSize: 14,
    color: '#78350F',
    flex: 1,
    lineHeight: 20,
  },
  editedTime: {
    fontSize: 11,
    color: '#92400E',
    marginTop: 10,
    fontStyle: 'italic',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerEmoji: {
    fontSize: 24,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 12,
  },
  circleTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3E8FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
    gap: 6,
    marginBottom: 20,
  },
  circleTagText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#7C3AED',
  },
  section: {
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  description: {
    fontSize: 16,
    color: '#334155',
    lineHeight: 24,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 24,
  },
  infoItem: {
    minWidth: '45%',
  },
  infoLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#94A3B8',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0F172A',
  },
  xpBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  xpText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#F59E0B',
  },
  proofBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  proofText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#7C3AED',
  },
  actions: {
    gap: 12,
    marginTop: 8,
  },
  acceptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    paddingVertical: 16,
    borderRadius: 14,
    gap: 8,
  },
  acceptButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  declineButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEF2F2',
    paddingVertical: 16,
    borderRadius: 14,
    gap: 8,
  },
  declineButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#EF4444',
  },
});

// Decline Modal Styles
export const declineModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
    width: SCREEN_WIDTH - 40,
  },
  header: {
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 16,
    alignItems: 'center',
  },
  iconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FEF2F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 22,
  },
  inputContainer: {
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    fontSize: 16,
    color: '#0F172A',
    minHeight: 100,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  charCount: {
    fontSize: 12,
    color: '#94A3B8',
    textAlign: 'right',
    marginTop: 6,
  },
  chipsContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#F8FAFC',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  chipSelected: {
    backgroundColor: '#EDE9FE',
    borderColor: '#8B5CF6',
  },
  chipText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  chipTextSelected: {
    color: '#8B5CF6',
  },
  actions: {
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  declineButton: {
    paddingVertical: 16,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  declineButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#EF4444',
  },
  cancelButton: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#8B5CF6',
  },
});

// Selection Mode Styles (WhatsApp style)
export const selectionStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#7C3AED',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 16,
  },
  cancelButton: {
    padding: 4,
  },
  headerText: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  deleteButton: {
    padding: 4,
  },
  checkboxRow: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    backgroundColor: '#7C3AED',
    borderColor: '#7C3AED',
  },
  selectedCard: {
    borderWidth: 2,
    borderColor: '#7C3AED',
    backgroundColor: 'rgba(124, 58, 237, 0.05)',
  },
});

// Action Sheet Styles
export const actionSheetStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  container: {
    margin: 8,
    marginBottom: 34,
    borderRadius: 14,
    overflow: 'hidden',
  },
  blur: {
    overflow: 'hidden',
    borderRadius: 14,
  },
  content: {
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  handle: {
    width: 36,
    height: 5,
    backgroundColor: '#E2E8F0',
    borderRadius: 3,
    alignSelf: 'center',
    marginBottom: 12,
  },
  title: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: 0.3,
  },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E2E8F0',
  },
  optionIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  optionText: {
    flex: 1,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0F172A',
  },
  optionSubtitle: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
  },
  infoText: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
    fontStyle: 'italic',
  },
  cancelButton: {
    marginTop: 8,
    paddingVertical: 16,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
  },
  cancelText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#EF4444',
  },
});

// Edit Modal Styles
export const editModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '85%',
    paddingBottom: 40,
  },
  handle: {
    width: 36,
    height: 5,
    backgroundColor: '#E2E8F0',
    borderRadius: 3,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E2E8F0',
  },
  cancelText: {
    fontSize: 17,
    color: '#8B5CF6',
  },
  title: {
    fontSize: 17,
    fontWeight: '600',
    color: '#0F172A',
  },
  saveText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#8B5CF6',
  },
  content: {
    padding: 20,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 8,
    marginTop: 16,
    letterSpacing: 0.3,
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#0F172A',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dateTimeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  dateTimeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dateTimeText: {
    fontSize: 15,
    color: '#0F172A',
  },
  xpRow: {
    flexDirection: 'row',
    gap: 10,
  },
  xpOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  xpOptionActive: {
    backgroundColor: '#FEF3C7',
    borderColor: '#F59E0B',
  },
  xpOptionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
  },
  xpOptionTextActive: {
    color: '#F59E0B',
  },
  toggleSection: {
    marginTop: 16,
    gap: 12,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
  },
  toggleInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  toggleLabel: {
    fontSize: 15,
    fontWeight: '500',
    color: '#0F172A',
  },
  toggle: {
    width: 51,
    height: 31,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
    padding: 2,
  },
  toggleActive: {
    backgroundColor: '#8B5CF6',
  },
  toggleKnob: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  toggleKnobActive: {
    transform: [{ translateX: 20 }],
  },
  frequencyRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
    marginLeft: 46,
  },
  frequencyOption: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: '#F8FAFC',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  frequencyOptionActive: {
    backgroundColor: '#EDE9FE',
    borderColor: '#8B5CF6',
  },
  frequencyText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#64748B',
  },
  frequencyTextActive: {
    color: '#8B5CF6',
  },
  infoNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    marginTop: 20,
  },
  infoNoteText: {
    fontSize: 13,
    color: '#64748B',
    flex: 1,
  },
  primaryButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 24,
  },
  primaryButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
    gap: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  dividerText: {
    fontSize: 13,
    color: '#94A3B8',
    fontWeight: '500',
  },
  acceptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#DCFCE7',
    borderRadius: 12,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  acceptButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#10B981',
  },
  acceptHint: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 12,
    lineHeight: 18,
  },
});
