import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scrollView: { flex: 1 },
  
  // Header
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12 },
  backButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: '#0F172A' },
  addButton: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#0F172A', alignItems: 'center', justifyContent: 'center' },
  
  // Toast
  toast: { position: 'absolute', top: 10, left: 20, right: 20, zIndex: 10, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 14, alignItems: 'center' },
  toastSuccess: { backgroundColor: '#ECFDF5' },
  toastInfo: { backgroundColor: '#F1F5F9' },
  toastText: { fontSize: 12, color: '#0F172A', fontWeight: '700' },
  
  // Stats Banner
  statsBanner: { marginHorizontal: 20, marginBottom: 16, padding: 16, borderRadius: 16, backgroundColor: '#FFFFFF', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statsLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  streakIconContainer: { width: 56, height: 56, borderRadius: 16, backgroundColor: '#F97316', alignItems: 'center', justifyContent: 'center' },
  streakValueRow: { flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  streakValue: { fontSize: 24, fontWeight: '900', color: '#0F172A' },
  streakLabel: { fontSize: 14, color: '#64748B' },
  xpRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  xpText: { fontSize: 13, fontWeight: '600', color: '#8B5CF6' },
  levelText: { fontSize: 11, color: '#94A3B8' },
  statsRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  rankInfo: { alignItems: 'flex-end' },
  rankRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  rankValue: { fontSize: 20, fontWeight: 'bold', color: '#0F172A' },
  rankTotal: { fontSize: 11, color: '#64748B' },
  trophyContainer: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#FEF3C7', alignItems: 'center', justifyContent: 'center' },
  xpProgressContainer: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  xpProgressLabels: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  xpProgressLabel: { fontSize: 11, color: '#64748B' },
  xpProgressValue: { fontSize: 11, fontWeight: '500', color: '#8B5CF6' },
  xpProgressBar: { height: 8, backgroundColor: '#F1F5F9', borderRadius: 4, overflow: 'hidden' },
  xpProgressFill: { height: '100%', backgroundColor: '#8B5CF6', borderRadius: 4 },
  
  // Tabs
  tabContainer: { paddingHorizontal: 20, marginBottom: 16 },
  tabBar: { flexDirection: 'row', gap: 4, padding: 4, backgroundColor: '#F1F5F9', borderRadius: 12 },
  tab: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12, borderRadius: 10, minHeight: 44 },
  tabActive: { backgroundColor: '#FFFFFF', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  tabText: { fontSize: 13, fontWeight: '500', color: '#64748B' },
  tabTextActive: { color: '#0F172A' },
  
  // Content
  content: { paddingHorizontal: 20 },
  challengesList: { gap: 16 },
  
  // Invite Card
  inviteCard: { padding: 16, borderRadius: 16, backgroundColor: '#FFFBEB', borderWidth: 1, borderColor: '#FDE68A' },
  inviteHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  inviteHeaderText: { fontSize: 13, fontWeight: '600', color: '#B45309' },
  inviteContent: { flexDirection: 'row', alignItems: 'center' },
  inviteIconContainer: { width: 44, height: 44, borderRadius: 12, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  inviteInfo: { flex: 1, marginLeft: 12 },
  inviteName: { fontSize: 15, fontWeight: '600', color: '#0F172A' },
  inviteDetails: { fontSize: 12, color: '#64748B', marginTop: 2 },
  inviteActions: { flexDirection: 'row', gap: 8 },
  declineButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, backgroundColor: '#FFFFFF', minHeight: 44, justifyContent: 'center' },
  joinButton: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, backgroundColor: '#0F172A', minHeight: 44, justifyContent: 'center' },
  joinButtonText: { fontSize: 13, fontWeight: '500', color: '#FFFFFF' },
  
  // Challenge Card
  challengeCard: { borderRadius: 16, backgroundColor: '#FFFFFF', overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  challengeHeader: { padding: 16 },
  challengeHeaderContent: { flexDirection: 'row', alignItems: 'center' },
  challengeIconContainer: { width: 48, height: 48, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  challengeHeaderInfo: { flex: 1, marginLeft: 12 },
  challengeHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  challengeOptionsButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  challengeName: { fontSize: 17, fontWeight: 'bold', color: '#FFFFFF' },
  challengeMeta: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  challengeMetaText: { fontSize: 12, color: 'rgba(255,255,255,0.8)' },
  challengeMetaDot: { fontSize: 12, color: 'rgba(255,255,255,0.6)', marginHorizontal: 4 },
  completedBadge: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  streakBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)' },
  streakBadgeText: { fontSize: 14, fontWeight: 'bold', color: '#FFFFFF' },
  challengeProgress: { marginTop: 16 },
  challengeProgressLabels: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  challengeProgressLabel: { fontSize: 11, color: 'rgba(255,255,255,0.7)' },
  challengeProgressBar: { height: 8, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 4, overflow: 'hidden' },
  challengeProgressFill: { height: '100%', backgroundColor: '#FFFFFF', borderRadius: 4 },
  challengeBody: { padding: 16 },
  todayStatus: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  todayPrompt: { flex: 1, fontSize: 13, color: '#64748B', marginLeft: 8 },
  todayCount: { fontSize: 12, fontWeight: '500', color: '#64748B' },
  
  // Mini Leaderboard
  miniLeaderboard: {
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  miniLeaderboardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  miniLeaderboardTitle: { fontSize: 12, fontWeight: '600', color: '#475569' },
  miniLeaderboardCta: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  miniLeaderboardHint: { fontSize: 11, color: '#94A3B8', fontWeight: '600' },
  memberAvatars: { flexDirection: 'row', gap: 8 },
  memberAvatarContainer: { position: 'relative' },
  memberAvatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#FFFFFF' },
  memberAvatarYou: { borderColor: '#8B5CF6' },
  memberAvatarText: { fontSize: 12, fontWeight: '600', color: '#FFFFFF' },
  rankBadge: { position: 'absolute', top: -4, right: -4, width: 16, height: 16, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  rankBadge1: { backgroundColor: '#FCD34D' },
  rankBadge2: { backgroundColor: '#D1D5DB' },
  rankBadge3: { backgroundColor: '#FDE68A' },
  rankBadgeText: { fontSize: 8, fontWeight: 'bold', color: '#78350F' },
  
  // Expanded Leaderboard
  expandedLeaderboard: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#F1F5F9', gap: 8 },
  leaderboardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 8, borderRadius: 12 },
  leaderboardRowYou: { backgroundColor: '#F5F3FF' },
  leaderboardRowLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  leaderboardRank: { width: 24, fontSize: 13, fontWeight: 'bold', color: '#94A3B8' },
  leaderboardRankTop: { color: '#D97706' },
  leaderboardAvatar: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  leaderboardAvatarText: { fontSize: 11, fontWeight: '600', color: '#FFFFFF' },
  leaderboardName: { fontSize: 14, fontWeight: '500', color: '#475569' },
  leaderboardNameYou: { color: '#7C3AED' },
  leaderboardStreak: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  leaderboardStreakText: { fontSize: 14, fontWeight: 'bold', color: '#F97316' },
  
  // Stakes Badge
  stakesBadge: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, backgroundColor: '#FFF1F2', marginBottom: 12 },
  stakesEmoji: { fontSize: 12 },
  stakesText: { fontSize: 12, fontWeight: '500', color: '#BE123C' },
  
  // Submit Button
  submitButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 12, borderRadius: 12, backgroundColor: '#0F172A', minHeight: 44 },
  submitButtonText: { fontSize: 15, fontWeight: '600', color: '#FFFFFF' },
  completedButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 12, borderRadius: 12, backgroundColor: '#ECFDF5' },
  completedButtonText: { fontSize: 15, fontWeight: '600', color: '#059669' },
  
  // Leaderboard Tab
  leaderboardTab: { gap: 16 },
  timeframeSelector: { flexDirection: 'row', gap: 8 },
  timeframeButton: { flex: 1, paddingVertical: 8, borderRadius: 12, backgroundColor: '#FFFFFF', alignItems: 'center' },
  timeframeButtonActive: { backgroundColor: '#0F172A' },
  timeframeButtonText: { fontSize: 13, fontWeight: '500', color: '#64748B' },
  timeframeButtonTextActive: { color: '#FFFFFF' },
  podiumCard: { padding: 16, borderRadius: 16, backgroundColor: '#FFFFFF' },
  podium: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', gap: 12 },
  podiumPosition: { alignItems: 'center' },
  podiumPosition1: { marginTop: -16 },
  podiumAvatar: { width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center', borderWidth: 4, marginBottom: 8 },
  podiumAvatar1: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#F97316', borderColor: '#FDE68A' },
  podiumAvatar2: { backgroundColor: '#94A3B8', borderColor: '#E2E8F0' },
  podiumAvatar3: { backgroundColor: '#FCD34D', borderColor: '#FDE68A' },
  podiumAvatarYou: { backgroundColor: '#8B5CF6', borderColor: '#C4B5FD' },
  podiumAvatarText: { fontSize: 20, fontWeight: 'bold', color: '#FFFFFF' },
  podiumAvatarText1: { fontSize: 24, fontWeight: 'bold', color: '#FFFFFF' },
  podiumName: { fontSize: 13, fontWeight: '600', color: '#475569' },
  podiumName1: { fontSize: 14, fontWeight: 'bold', color: '#0F172A' },
  podiumNameYou: { color: '#7C3AED' },
  podiumXP: { fontSize: 11, color: '#64748B', marginTop: 2 },
  podiumXP1: { fontSize: 12, color: '#D97706', fontWeight: '500' },
  podiumStand: { marginTop: 8, borderTopLeftRadius: 8, borderTopRightRadius: 8, alignItems: 'center', justifyContent: 'center' },
  podiumStand1: { width: 96, height: 96, backgroundColor: '#FDE68A' },
  podiumStand2: { width: 80, height: 64, backgroundColor: '#E2E8F0' },
  podiumStand3: { width: 80, height: 48, backgroundColor: '#FEF3C7' },
  podiumStandYou: { backgroundColor: '#EDE9FE' },
  podiumNumber: { fontSize: 24, fontWeight: '900', color: '#94A3B8' },
  podiumNumber1: { fontSize: 32, color: '#B45309' },
  podiumNumberYou: { color: '#8B5CF6' },
  fullLeaderboard: { borderRadius: 16, backgroundColor: '#FFFFFF', overflow: 'hidden' },
  leaderboardItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  leaderboardItemYou: { backgroundColor: '#F5F3FF' },
  leaderboardItemLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  leaderboardItemRank: { width: 32, fontSize: 15, fontWeight: 'bold', color: '#94A3B8' },
  leaderboardItemAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#94A3B8', alignItems: 'center', justifyContent: 'center' },
  leaderboardItemAvatarYou: { backgroundColor: '#8B5CF6' },
  leaderboardItemAvatarText: { fontSize: 14, fontWeight: 'bold', color: '#FFFFFF' },
  leaderboardItemName: { fontSize: 15, fontWeight: '600', color: '#334155' },
  leaderboardItemNameYou: { color: '#7C3AED' },
  leaderboardItemMeta: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  leaderboardItemXP: { fontSize: 12, color: '#64748B' },
  leaderboardItemDot: { color: '#94A3B8' },
  leaderboardItemStreak: { fontSize: 12, color: '#F97316' },
  leaderboardItemRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  leaderboardItemWins: { fontSize: 13, fontWeight: '500', color: '#64748B' },
  
  // Achievements Tab
  achievementsTab: { gap: 12 },
  achievementStats: { flexDirection: 'row', gap: 8, marginBottom: 4 },
  achievementStat: { flex: 1, padding: 12, borderRadius: 12, backgroundColor: '#FFFFFF', alignItems: 'center' },
  achievementStatValue: { fontSize: 20, fontWeight: 'bold' },
  achievementStatLabel: { fontSize: 10, color: '#64748B', marginTop: 2 },
  achievementCard: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 16, backgroundColor: '#FFFFFF' },
  achievementCardLocked: { opacity: 0.7 },
  achievementIcon: { width: 56, height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  achievementIconUnlocked: { backgroundColor: '#FEF3C7' },
  achievementIconLocked: { backgroundColor: '#F1F5F9' },
  achievementInfo: { flex: 1, marginLeft: 16 },
  achievementTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  achievementName: { fontSize: 15, fontWeight: '600', color: '#0F172A' },
  achievementNameLocked: { color: '#64748B' },
  achievementDescription: { fontSize: 12, color: '#64748B', marginTop: 2 },
  achievementProgress: { marginTop: 8 },
  achievementProgressLabels: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  achievementProgressText: { fontSize: 10, color: '#94A3B8' },
  achievementProgressBar: { height: 6, backgroundColor: '#E2E8F0', borderRadius: 3, overflow: 'hidden' },
  achievementProgressFill: { height: '100%', backgroundColor: '#8B5CF6', borderRadius: 3 },
  achievementXP: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  achievementXPUnlocked: { backgroundColor: '#ECFDF5' },
  achievementXPLocked: { backgroundColor: '#F1F5F9' },
  achievementXPText: { fontSize: 12, fontWeight: 'bold' },
  achievementXPTextUnlocked: { color: '#059669' },
  achievementXPTextLocked: { color: '#64748B' },
  
  // Modal Styles
  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 32, width: '100%', maxWidth: 390, alignSelf: 'center' },
  modalHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#E2E8F0', alignSelf: 'center', marginBottom: 12 },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A', marginBottom: 12 },
  modalLabel: { fontSize: 12, color: '#94A3B8', fontWeight: '700', textTransform: 'uppercase', marginBottom: 8 },
  modalInput: { backgroundColor: '#F1F5F9', borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, fontSize: 14, color: '#0F172A', marginBottom: 12 },
  choiceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  choiceChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 14, backgroundColor: '#F1F5F9' },
  choiceChipActive: { backgroundColor: '#0F172A' },
  choiceText: { fontSize: 12, color: '#64748B', fontWeight: '600' },
  choiceTextActive: { color: '#FFFFFF' },
  modalActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  modalCancel: { flex: 1, paddingVertical: 12, borderRadius: 12, backgroundColor: '#F1F5F9', alignItems: 'center' },
  modalCancelText: { color: '#64748B', fontWeight: '700' },
  modalSave: { flex: 1, paddingVertical: 12, borderRadius: 12, backgroundColor: '#0F172A', alignItems: 'center' },
  modalSaveText: { color: '#FFFFFF', fontWeight: '700' },
  
  // Chip Selectors
  chipScroll: { marginBottom: 12, marginHorizontal: -4 },
  categoryEmoji: { fontSize: 14, marginRight: 4 },
  numChip: { 
    alignItems: 'center', 
    justifyContent: 'center',
    paddingHorizontal: 16, 
    paddingVertical: 10, 
    borderRadius: 14, 
    backgroundColor: '#F1F5F9',
    minWidth: 60,
  },
  numChipActive: { backgroundColor: '#0F172A' },
  numChipValue: { fontSize: 16, fontWeight: '700', color: '#0F172A' },
  numChipValueActive: { color: '#FFFFFF' },
  numChipLabel: { fontSize: 10, color: '#94A3B8', marginTop: 2 },
  numChipLabelActive: { color: 'rgba(255,255,255,0.7)' },
  xpChip: { backgroundColor: '#F5F3FF' },
  xpChipActive: { backgroundColor: '#8B5CF6' },
  xpChipValueActive: { color: '#FFFFFF' },
  xpChipLabelActive: { color: 'rgba(255,255,255,0.7)' },
  circleChip: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 6,
    paddingHorizontal: 16, 
    paddingVertical: 12, 
    borderRadius: 14, 
    backgroundColor: '#F1F5F9',
    minHeight: 44,
    marginRight: 8,
  },
  circleChipActive: { backgroundColor: '#0F172A' },
  circleEmoji: { fontSize: 14 },
  circleChipText: { fontSize: 13, fontWeight: '600', color: '#64748B' },
  circleChipTextActive: { color: '#FFFFFF' },
  
  // Options Modal
  optionsOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
  optionsSheet: { 
    backgroundColor: '#FFFFFF', 
    borderRadius: 20, 
    padding: 20, 
    width: '85%', 
    maxWidth: 320,
  },
  optionsHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#E2E8F0', alignSelf: 'center', marginBottom: 16 },
  optionsTitle: { fontSize: 16, fontWeight: '700', color: '#0F172A', textAlign: 'center', marginBottom: 16 },
  optionItem: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 12, 
    paddingVertical: 14, 
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  optionItemWarning: { backgroundColor: '#FFF7ED', borderWidth: 1, borderColor: '#FED7AA' },
  optionItemDanger: { marginTop: 8, backgroundColor: '#FEF2F2', borderWidth: 1, borderColor: '#FECACA' },
  optionText: { fontSize: 15, fontWeight: '500', color: '#0F172A' },
});
