import { StyleSheet } from 'react-native';
import { Colors } from './constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.white },
  backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center', marginRight: 8 },
  headerTitle: { flex: 1 },
  title: { fontSize: 20, fontWeight: '700', color: Colors.textPrimary },
  subtitle: { fontSize: 13, color: Colors.textSecondary, marginTop: 2 },
  aiSortButton: { marginLeft: 12 },
  aiSortGradient: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  content: { flex: 1 },
  infoBanner: { margin: 16, borderRadius: 16, overflow: 'hidden' },
  infoBannerGradient: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12 },
  infoBannerIcon: { width: 48, height: 48, borderRadius: 24, overflow: 'hidden' },
  infoBannerIconGradient: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  infoBannerContent: { flex: 1 },
  infoBannerTitle: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary },
  infoBannerSubtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  autoPlanButton: { backgroundColor: Colors.primary, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20 },
  autoPlanButtonText: { color: Colors.white, fontSize: 13, fontWeight: '600' },
  quickAddContainer: { paddingHorizontal: 16, marginBottom: 12 },
  quickAddInput: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, gap: 10, borderWidth: 1, borderColor: Colors.border },
  textInput: { flex: 1, fontSize: 15, color: Colors.textPrimary, padding: 0 },
  micButton: { padding: 4 },
  addButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.primary, justifyContent: 'center', alignItems: 'center' },
  addButtonDisabled: { backgroundColor: Colors.surface },
  templatesScroll: { marginBottom: 12 },
  templatesContent: { paddingHorizontal: 16, gap: 8 },
  templateButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, gap: 6, borderWidth: 1, borderColor: Colors.border, marginRight: 8 },
  templateText: { fontSize: 13, color: Colors.textSecondary, fontWeight: '500' },
  filterTabs: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 12 },
  filterTab: { flex: 1, paddingVertical: 10, alignItems: 'center', backgroundColor: Colors.white, borderRadius: 10, borderWidth: 1, borderColor: Colors.border },
  filterTabActive: { backgroundColor: Colors.textPrimary, borderColor: Colors.textPrimary },
  filterTabText: { fontSize: 13, fontWeight: '600', color: Colors.textSecondary },
  filterTabTextActive: { color: Colors.white },
  quickAccessGrid: { flexDirection: 'row', paddingHorizontal: 16, gap: 12, marginBottom: 16 },
  quickAccessButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.white, paddingVertical: 14, borderRadius: 12, gap: 8, borderWidth: 1, borderColor: Colors.border },
  quickAccessText: { fontSize: 14, fontWeight: '600', color: Colors.textPrimary },
  taskList: { paddingHorizontal: 16 },
  taskCard: { flexDirection: 'row', backgroundColor: Colors.white, borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: Colors.border },
  checkbox: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: Colors.border, justifyContent: 'center', alignItems: 'center', marginRight: 12, marginTop: 2 },
  checkboxCompleted: { backgroundColor: Colors.success, borderColor: Colors.success },
  taskContent: { flex: 1 },
  taskHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 8 },
  taskTitle: { flex: 1, fontSize: 15, fontWeight: '500', color: Colors.textPrimary, lineHeight: 20 },
  taskActions: { flexDirection: 'row', alignItems: 'center', gap: 8, marginLeft: 8 },
  moreButton: { padding: 2 },
  taskMenu: { position: 'absolute', top: 30, right: 0, backgroundColor: Colors.white, borderRadius: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8, elevation: 8, zIndex: 100, minWidth: 150, borderWidth: 1, borderColor: Colors.border },
  taskMenuItem: { flexDirection: 'row', alignItems: 'center', padding: 12, gap: 10, borderBottomWidth: 1, borderBottomColor: Colors.border },
  taskMenuItemText: { fontSize: 14, color: Colors.textPrimary },
  taskMeta: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6, marginBottom: 10 },
  badge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, gap: 4 },
  badgeText: { fontSize: 11, fontWeight: '600' },
  taskTime: { fontSize: 11, color: Colors.textMuted, marginLeft: 'auto' },
  taskButtons: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  addToPlanButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.successLight, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, gap: 4 },
  addToPlanButtonText: { fontSize: 12, fontWeight: '600', color: Colors.success },
  categorizeButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.primaryLight, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, gap: 4 },
  categorizeButtonText: { fontSize: 12, fontWeight: '600', color: Colors.primary },
  deleteButton: { padding: 6, marginLeft: 'auto' },
  emptyState: { alignItems: 'center', paddingVertical: 60 },
  emptyIcon: { marginBottom: 16 },
  emptyTitle: { fontSize: 18, fontWeight: '600', color: Colors.textPrimary, marginBottom: 8 },
  emptySubtitle: { fontSize: 14, color: Colors.textSecondary, marginBottom: 20 },
  emptyButton: { backgroundColor: Colors.primary, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 10 },
  emptyButtonText: { color: Colors.white, fontSize: 15, fontWeight: '600' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: Colors.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '85%', width: '100%', maxWidth: 390, alignSelf: 'center' },
  aiModalSheet: { backgroundColor: Colors.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '90%', width: '100%', maxWidth: 390, alignSelf: 'center' },
  sheetHandle: { width: 40, height: 4, backgroundColor: Colors.border, borderRadius: 2, alignSelf: 'center', marginBottom: 20 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 20 },
  modalHeaderIcon: { width: 48, height: 48, borderRadius: 24, backgroundColor: Colors.primaryLight, justifyContent: 'center', alignItems: 'center' },
  modalTitle: { fontSize: 20, fontWeight: '700', color: Colors.textPrimary },
  modalSubtitle: { fontSize: 14, color: Colors.textSecondary, marginTop: 2 },
  taskPreview: { backgroundColor: Colors.surface, padding: 14, borderRadius: 10, marginBottom: 20 },
  taskPreviewText: { fontSize: 15, color: Colors.textPrimary, fontWeight: '500' },
  dateOptionsScroll: { maxHeight: 350 },
  dateOptions: { gap: 8, marginBottom: 20 },
  dateOption: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.surface, padding: 14, borderRadius: 10, borderWidth: 2, borderColor: 'transparent' },
  dateOptionSelected: { backgroundColor: Colors.successLight, borderColor: Colors.success },
  dateOptionContent: { flex: 1 },
  dateOptionLabel: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary },
  dateOptionLabelSelected: { color: Colors.success },
  dateOptionDate: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  dateOptionDateSelected: { color: Colors.success },
  recommendedBadge: { backgroundColor: Colors.primaryLight, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8, marginTop: 4, alignSelf: 'flex-start' },
  recommendedBadgeText: { fontSize: 10, fontWeight: '600', color: Colors.primary },
  dateCheckmark: { width: 24, height: 24, borderRadius: 12, backgroundColor: Colors.success, justifyContent: 'center', alignItems: 'center' },
  modalButtons: { flexDirection: 'row', gap: 12 },
  cancelButton: { flex: 1, paddingVertical: 14, borderRadius: 12, backgroundColor: Colors.surface, alignItems: 'center' },
  cancelButtonText: { fontSize: 16, fontWeight: '600', color: Colors.textSecondary },
  confirmButton: { flex: 1, flexDirection: 'row', paddingVertical: 14, borderRadius: 12, backgroundColor: Colors.success, alignItems: 'center', justifyContent: 'center', gap: 8 },
  confirmButtonText: { fontSize: 16, fontWeight: '600', color: Colors.white },
  processingContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
  processingText: { fontSize: 16, color: Colors.textSecondary, marginTop: 20 },
  aiModalHeader: { alignItems: 'center', marginBottom: 24 },
  aiModalIcon: { width: 64, height: 64, borderRadius: 32, overflow: 'hidden', marginBottom: 16 },
  aiModalIconGradient: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  aiModalTitle: { fontSize: 24, fontWeight: '700', color: Colors.textPrimary },
  aiModalSubtitle: { fontSize: 14, color: Colors.textSecondary, marginTop: 4 },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  statBox: { flex: 1, backgroundColor: Colors.surface, padding: 16, borderRadius: 12, alignItems: 'center' },
  statNumber: { fontSize: 24, fontWeight: '700', color: Colors.primary },
  statLabel: { fontSize: 12, color: Colors.textSecondary, marginTop: 4 },
  scheduleTitle: { fontSize: 16, fontWeight: '600', color: Colors.textPrimary, marginBottom: 12 },
  scheduleList: { maxHeight: 250, marginBottom: 16 },
  scheduleItem: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border, gap: 12 },
  scheduleTime: { fontSize: 13, fontWeight: '600', color: Colors.primary, width: 70 },
  scheduleContent: { flex: 1 },
  scheduleTaskTitle: { fontSize: 14, fontWeight: '500', color: Colors.textPrimary, marginBottom: 6 },
  scheduleTaskMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  smallBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, gap: 4 },
  smallBadgeText: { fontSize: 10, fontWeight: '600' },
  scheduleTaskTime: { fontSize: 11, color: Colors.textMuted },
  priorityEmoji: { fontSize: 12 },
  helperText: { fontSize: 12, color: Colors.textMuted, textAlign: 'center', marginBottom: 16 },
});
